name: CI/CD for Node.js App

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        echo "NPM install done"

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-gh-actions .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-gh-actions:latest ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-gh-actions:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-gh-actions:latest

